### ISSUE TITLE
Q: Are you going to deploy this into maven central?

### ISSUE THREAD

**Issue by rob-bygrave** [robaho/httpserver#1]
I'd be keen to have a play.  I have a "routing layer" that I can put on top of it. I also have source code generation for controllers to the "routing layer" for Helidon 4, Javalin, Grizzly and the JDK http server.  

Ref: https://github.com/avaje/avaje-http for the controller api (e.g. `@Get`, `@Post` etc) and annotation processors that target Helidon 4 etc

**Comment by robaho** [comment]
I plan to. Haven’t done it before so need to figure out the process.

**Comment by robaho** [comment]
It has been published to maven. Might take a bit for it to be visible.

```xml
<dependency>
  <groupId>io.github.robaho</groupId>
  <artifactId>httpserver</artifactId>
  <version>1.0.1</version>
</dependency>
```
