### ISSUE TITLE
Add JPMS support?

### ISSUE THREAD

**Issue by SentryMan** [robaho/httpserver#4]
Adding a module-info allows applications to take full advantage of stuff like JLink and JPackage among other things.

**Comment by robaho** [comment]
I will certainly look into it but as a stand-alone jar I am not sure how beneficial it would be. I guess it could limit some dependencies but the packing author could just as easily do that.

**Comment by robaho** [comment]
Also, the jdk.httpserver module contains both the required interfaces and the unneeded standard implementation. I will take a look.

**Comment by SentryMan** [comment]
Jlink/Jpackage are a little temperamental in _that every single dependency_  used by a project has to have a `module-info.java` file or else their native optimizations are kaput.

Since you have no external dependencies it may be as simple as 

```java
module robaho.httpserver {
    requires jdk.httpserver;
}
```

**Comment by robaho** [comment]
Yea. That’s what I assumed. I am not familiar with those tools but I figured they would have an override capability making this unnecessary. I’ll see if I can get it enabled tomorrow.

**Comment by robaho** [comment]
pushing version 1.0.9 today - with updated performance numbers - it is more than 10x faster than the JDK version...

**Comment by robaho** [comment]
I posted to the open JDK net dev list but I think it was suppressed.

**Comment by SentryMan** [comment]
net dev does seem to have a deluge of posts.
